### ISSUE TITLE
Incorrect module resolution when there are identical relative imports in the main & aliased (reference) projects

### ISSUE THREAD

**Issue by Aveyder** [dividab/tsconfig-paths-webpack-plugin#83]
I don't know why, but it looks like `TSConfigPathsPlugin` doesn't work fine when aliasing a reference project that contains a relative import with the same folder and module names as the main project has. 

Here is a repro: https://github.com/Aveyder/tsconfig-paths-issue-repro

**Comment by voliva** [comment]
I just ran across this, and found a posible solution on #85 

I've tested it with https://www.npmjs.com/package/patch-package and seems to be working fine on a considerably big project. Can anyone give it a try?

**Comment by flytam** [comment]
Hey @Rush @voliva !. I also encountered this situation, here is an [example](https://github.com/flytam/tsconfig-paths-webpack-plugin-err)  and I found out the cause of this problem.
![image](https://user-images.githubusercontent.com/20512530/139782839-9b2f7971-b014-45b3-936b-ec538b6ffc45.png)

There is a `lib/axios` file in the project code. Also, `index. ts` has code to import `axios`. 

When`require('./lib/axios')` in `node_modules/axios/index.js` is executed, `getInnerRequest` returns `lib/axios`. The `matchPath` function then looks for `lib/axios` and returns when it finds the `lib/axios` file in the project. The correct behavior would be to look for `axios/lib/axios` in `node_modules`. 

This happens because `getInnerRequest` uses `innerRequest = resolver.join(Request.relativePath, innerRequest); `. And for the request file,the relativePath is relative to the corresponding file request package directory (relativePath code logic can be found in `enhanced-resolve/lib/DescriptionFilePlugin`). 

In the above case, `request.relativePath` is `. ` (the relativePath of `axios/index.js` to the package `axios`), resulting in a concatenated path `lib/axios`, which happens to be in the project. 

I think the fixes mentioned above are correct, because the relative path plugin itself should not be handled relative path.The logic used in the original code to determine the relative path is wrong because the return value of `getinnerRequest` does not start with the relative path all time.
```
        if (!innerRequest ||
            innerRequest.startsWith(".") ||
            innerRequest.startsWith("..")) {
            return callback();
        }
```

IMG1
![image](https://user-images.githubusercontent.com/20512530/139783162-2d7a3171-fd1b-49f4-8a80-2b5dd276a2c2.png)

IMG2
![image](https://user-images.githubusercontent.com/20512530/139783259-a3494e7f-789f-442d-a62f-f65289aa7a88.png)

IMG3
![image](https://user-images.githubusercontent.com/20512530/139783627-f7d6ac50-de67-4979-90cd-105a724c7b39.png)
